"""test

Revision ID: 67351b646275
Revises: 
Create Date: 2026-07-17 18:10:55.312253

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '67351b646275'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
