"""initial domain schema

Revision ID: a3542ee22962
Revises: 
Create Date: 2026-07-17 20:16:07.434512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3542ee22962'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_versions_document_id_version')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('logical_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'node_key', name='uq_logical_nodes_document_id_node_key')
    )
    op.create_index(op.f('ix_logical_nodes_document_id'), 'logical_nodes', ['document_id'], unique=False)
    op.create_table('node_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logical_node_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('markdown_level', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logical_node_id'], ['logical_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_node_id', 'document_version_id', name='uq_node_versions_logical_node_id_document_version_id')
    )
    op.create_index(op.f('ix_node_versions_document_version_id'), 'node_versions', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_node_versions_logical_node_id'), 'node_versions', ['logical_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_versions_logical_node_id'), table_name='node_versions')
    op.drop_index(op.f('ix_node_versions_document_version_id'), table_name='node_versions')
    op.drop_table('node_versions')
    op.drop_index(op.f('ix_logical_nodes_document_id'), table_name='logical_nodes')
    op.drop_table('logical_nodes')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
